import XCTest
@testable import KTDatabasePlugin

final class PostgresCreateStatementRenderTests: XCTestCase {
    func testRendersColumnsConstraintsAndIndexes() throws {
        let sql = try PostgresDriver.renderTable(
            qualifiedName: "\"public\".\"users\"",
            columns: [
                PostgresColumnDDL(name: "id", type: "integer", notNull: true, defaultExpression: nil, identity: "d", generated: ""),
                PostgresColumnDDL(name: "email", type: "text", notNull: false, defaultExpression: "'x'::text", identity: "", generated: ""),
                PostgresColumnDDL(name: "slug", type: "text", notNull: false, defaultExpression: "lower(email)", identity: "", generated: "s"),
            ],
            constraints: [(name: "users_pkey", definition: "PRIMARY KEY (id)")],
            indexes: ["CREATE INDEX users_email_idx ON public.users USING btree (email)"]
        )
        XCTAssertEqual(sql, """
        CREATE TABLE "public"."users" (
            "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            "email" text DEFAULT 'x'::text,
            "slug" text GENERATED ALWAYS AS (lower(email)) STORED,
            CONSTRAINT "users_pkey" PRIMARY KEY (id)
        );

        CREATE INDEX users_email_idx ON public.users USING btree (email);
        """)
    }

    func testViewKeepsSingleTerminator() {
        let sql = PostgresDriver.renderView(qualifiedName: "\"public\".\"v\"", definition: " SELECT 1;\n")
        XCTAssertEqual(sql, "CREATE VIEW \"public\".\"v\" AS\nSELECT 1;")
    }
}
